version: 2.1

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - test
      - build:
          requires:
            - test

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: node:16

    steps:
      - checkout
      - run: yarn prod:build
  test:
    docker:
      - image: node:16
    steps:
      - checkout
      - run: yarn test
